#############################################################################
# Makefile for building: libmere-utils.so.0.0.1b
# Generated by qmake (3.1) (Qt 5.15.0)
# Project:  mere-utils-lib.pro
# Template: lib
# Command: /usr/local/lib/qt5/bin/qmake -o Makefile mere-utils-lib.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DMERE_UTILS_LIB -DLIB_CODE=\"mere-utils\" -DLIB_NAME=\"mere-utils\" -DLIB_VERSION=\"0.0.1b\" -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -pthread -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -pthread -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtCore -I. -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang
QMAKE         = /usr/local/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mere-utils0.0.1b
DISTDIR = /usr/home/iklash/workspace/mere-utils/mere-utils-lib/.tmp/mere-utils0.0.1b
LINK          = clang++
LFLAGS        = -pthread -Wl,-rpath,/usr/local/lib/qt5 -shared -Wl,-soname,libmere-utils.so.0
LIBS          = $(SUBLIBS) /usr/local/lib/qt5/libQt5Core.so  -L/usr/local/lib 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/apputils.cpp \
		src/envutils.cpp \
		src/fileutils.cpp \
		src/i18nutils.cpp \
		src/iconutils.cpp \
		src/processutils.cpp \
		src/signalutils.cpp \
		src/stringutils.cpp moc_apputils.cpp \
		moc_signalutils.cpp
OBJECTS       = apputils.o \
		envutils.o \
		fileutils.o \
		i18nutils.o \
		iconutils.o \
		processutils.o \
		signalutils.o \
		stringutils.o \
		moc_apputils.o \
		moc_signalutils.o
DIST          = /usr/local/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/lib/qt5/mkspecs/common/unix.conf \
		/usr/local/lib/qt5/mkspecs/common/bsd/bsd.conf \
		/usr/local/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/lib/qt5/mkspecs/common/clang.conf \
		/usr/local/lib/qt5/mkspecs/qconfig.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_declarative.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		/usr/local/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/local/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/local/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/lib/qt5/mkspecs/features/default_post.prf \
		/usr/local/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/local/lib/qt5/mkspecs/features/qt.prf \
		/usr/local/lib/qt5/mkspecs/features/resources_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/resources.prf \
		/usr/local/lib/qt5/mkspecs/features/moc.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/local/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/local/lib/qt5/mkspecs/features/yacc.prf \
		/usr/local/lib/qt5/mkspecs/features/lex.prf \
		mere-utils-lib.pro src/apputils.h \
		src/envutils.h \
		src/fileutils.h \
		src/global.h \
		src/i18nutils.h \
		src/iconutils.h \
		src/processutils.h \
		src/signalutils.h \
		src/stringutils.h src/apputils.cpp \
		src/envutils.cpp \
		src/fileutils.cpp \
		src/i18nutils.cpp \
		src/iconutils.cpp \
		src/processutils.cpp \
		src/signalutils.cpp \
		src/stringutils.cpp
QMAKE_TARGET  = mere-utils
DESTDIR       = 
TARGET        = libmere-utils.so.0.0.1b
TARGETA       = libmere-utils.a
TARGET0       = libmere-utils.so
TARGETD       = libmere-utils.so.0.0.1b
TARGET1       = libmere-utils.so.0
TARGET2       = libmere-utils.so.0.0


first: all
####### Build rules

libmere-utils.so.0.0.1b:  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: libmere-utils.a

libmere-utils.a:  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: mere-utils-lib.pro /usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf /usr/local/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/lib/qt5/mkspecs/common/unix.conf \
		/usr/local/lib/qt5/mkspecs/common/bsd/bsd.conf \
		/usr/local/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/lib/qt5/mkspecs/common/clang.conf \
		/usr/local/lib/qt5/mkspecs/qconfig.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_declarative.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		/usr/local/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/local/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/local/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/lib/qt5/mkspecs/features/default_post.prf \
		/usr/local/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/local/lib/qt5/mkspecs/features/qt.prf \
		/usr/local/lib/qt5/mkspecs/features/resources_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/resources.prf \
		/usr/local/lib/qt5/mkspecs/features/moc.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/local/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/local/lib/qt5/mkspecs/features/yacc.prf \
		/usr/local/lib/qt5/mkspecs/features/lex.prf \
		mere-utils-lib.pro
	$(QMAKE) -o Makefile mere-utils-lib.pro
/usr/local/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/local/lib/qt5/mkspecs/common/unix.conf:
/usr/local/lib/qt5/mkspecs/common/bsd/bsd.conf:
/usr/local/lib/qt5/mkspecs/common/sanitize.conf:
/usr/local/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/local/lib/qt5/mkspecs/common/clang.conf:
/usr/local/lib/qt5/mkspecs/qconfig.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_declarative.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_opengl.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_pdf.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/local/lib/qt5/mkspecs/features/qt_config.prf:
/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf:
/usr/local/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/local/lib/qt5/mkspecs/features/toolchain.prf:
/usr/local/lib/qt5/mkspecs/features/default_pre.prf:
/usr/local/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/local/lib/qt5/mkspecs/features/default_post.prf:
/usr/local/lib/qt5/mkspecs/features/warn_on.prf:
/usr/local/lib/qt5/mkspecs/features/qt.prf:
/usr/local/lib/qt5/mkspecs/features/resources_functions.prf:
/usr/local/lib/qt5/mkspecs/features/resources.prf:
/usr/local/lib/qt5/mkspecs/features/moc.prf:
/usr/local/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/local/lib/qt5/mkspecs/features/qmake_use.prf:
/usr/local/lib/qt5/mkspecs/features/file_copies.prf:
/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/local/lib/qt5/mkspecs/features/exceptions.prf:
/usr/local/lib/qt5/mkspecs/features/yacc.prf:
/usr/local/lib/qt5/mkspecs/features/lex.prf:
mere-utils-lib.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile mere-utils-lib.pro

qmake_all: FORCE


all: Makefile libmere-utils.so.0.0.1b

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/apputils.h src/envutils.h src/fileutils.h src/global.h src/i18nutils.h src/iconutils.h src/processutils.h src/signalutils.h src/stringutils.h $(DISTDIR)/
	$(COPY_FILE) --parents src/apputils.cpp src/envutils.cpp src/fileutils.cpp src/i18nutils.cpp src/iconutils.cpp src/processutils.cpp src/signalutils.cpp src/stringutils.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/lib/qt5/mkspecs/features/data/dummy.cpp
	clang++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_apputils.cpp moc_signalutils.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_apputils.cpp moc_signalutils.cpp
moc_apputils.cpp: src/apputils.h \
		src/global.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtCore/QObject \
		moc_predefs.h \
		/usr/local/lib/qt5/bin/moc
	/usr/local/lib/qt5/bin/moc $(DEFINES) --include /usr/home/iklash/workspace/mere-utils/mere-utils-lib/moc_predefs.h -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I/usr/home/iklash/workspace/mere-utils/mere-utils-lib -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtCore -I/usr/include/c++/v1 -I/usr/lib/clang/10.0.1/include -I/usr/include src/apputils.h -o moc_apputils.cpp

moc_signalutils.cpp: src/signalutils.h \
		src/global.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtCore/QObject \
		/usr/local/include/qt5/QtCore/QSocketNotifier \
		/usr/local/include/qt5/QtCore/qsocketnotifier.h \
		moc_predefs.h \
		/usr/local/lib/qt5/bin/moc
	/usr/local/lib/qt5/bin/moc $(DEFINES) --include /usr/home/iklash/workspace/mere-utils/mere-utils-lib/moc_predefs.h -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I/usr/home/iklash/workspace/mere-utils/mere-utils-lib -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtCore -I/usr/include/c++/v1 -I/usr/lib/clang/10.0.1/include -I/usr/include src/signalutils.h -o moc_signalutils.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

apputils.o: src/apputils.cpp src/apputils.h \
		src/global.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtCore/QObject \
		/usr/local/include/qt5/QtCore/QCoreApplication \
		/usr/local/include/qt5/QtCore/qcoreapplication.h \
		/usr/local/include/qt5/QtCore/qeventloop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o apputils.o src/apputils.cpp

envutils.o: src/envutils.cpp src/envutils.h \
		src/global.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtCore/QProcessEnvironment \
		/usr/local/include/qt5/QtCore/qprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o envutils.o src/envutils.cpp

fileutils.o: src/fileutils.cpp src/fileutils.h \
		src/global.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		src/stringutils.h \
		/usr/local/include/qt5/QtCore/QFileInfo \
		/usr/local/include/qt5/QtCore/qfileinfo.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtCore/QMimeDatabase \
		/usr/local/include/qt5/QtCore/qmimedatabase.h \
		/usr/local/include/qt5/QtCore/qmimetype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fileutils.o src/fileutils.cpp

i18nutils.o: src/i18nutils.cpp src/apputils.h \
		src/global.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtCore/QObject \
		src/i18nutils.h \
		/usr/local/include/qt5/QtCore/QTranslator \
		/usr/local/include/qt5/QtCore/qtranslator.h \
		/usr/local/include/qt5/QtCore/QLocale \
		src/stringutils.h \
		/usr/local/include/qt5/QtCore/QFileInfo \
		/usr/local/include/qt5/QtCore/qfileinfo.h \
		/usr/local/include/qt5/QtCore/qfile.h \
		/usr/local/include/qt5/QtCore/qfiledevice.h \
		/usr/local/include/qt5/QtCore/QCoreApplication \
		/usr/local/include/qt5/QtCore/qcoreapplication.h \
		/usr/local/include/qt5/QtCore/qeventloop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o i18nutils.o src/i18nutils.cpp

iconutils.o: src/iconutils.cpp src/iconutils.h \
		src/global.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iconutils.o src/iconutils.cpp

processutils.o: src/processutils.cpp src/processutils.h \
		src/global.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processutils.o src/processutils.cpp

signalutils.o: src/signalutils.cpp src/signalutils.h \
		src/global.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/local/include/qt5/QtCore/QObject \
		/usr/local/include/qt5/QtCore/QSocketNotifier \
		/usr/local/include/qt5/QtCore/qsocketnotifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signalutils.o src/signalutils.cpp

stringutils.o: src/stringutils.cpp src/stringutils.h \
		src/global.h \
		/usr/local/include/qt5/QtCore/qglobal.h \
		/usr/local/include/qt5/QtCore/qconfig-bootstrapped.h \
		/usr/local/include/qt5/QtCore/qconfig.h \
		/usr/local/include/qt5/QtCore/qconfig-modules.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-core.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-dbus.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-network.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-gui.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-widgets.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-concurrent.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-declarative.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-printsupport.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-opengl.h \
		/usr/local/include/qt5/QtCore/modules/qconfig-multimedia.h \
		/usr/local/include/qt5/QtCore/qtcore-config.h \
		/usr/local/include/qt5/QtCore/qsystemdetection.h \
		/usr/local/include/qt5/QtCore/qprocessordetection.h \
		/usr/local/include/qt5/QtCore/qcompilerdetection.h \
		/usr/local/include/qt5/QtCore/qtypeinfo.h \
		/usr/local/include/qt5/QtCore/qsysinfo.h \
		/usr/local/include/qt5/QtCore/qlogging.h \
		/usr/local/include/qt5/QtCore/qflags.h \
		/usr/local/include/qt5/QtCore/qatomic.h \
		/usr/local/include/qt5/QtCore/qbasicatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/local/include/qt5/QtCore/qgenericatomic.h \
		/usr/local/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/local/include/qt5/QtCore/qatomic_msvc.h \
		/usr/local/include/qt5/QtCore/qglobalstatic.h \
		/usr/local/include/qt5/QtCore/qmutex.h \
		/usr/local/include/qt5/QtCore/qnumeric.h \
		/usr/local/include/qt5/QtCore/qversiontagging.h \
		/usr/local/include/qt5/QtCore/QDebug \
		/usr/local/include/qt5/QtCore/qdebug.h \
		/usr/local/include/qt5/QtCore/qalgorithms.h \
		/usr/local/include/qt5/QtCore/qhash.h \
		/usr/local/include/qt5/QtCore/qchar.h \
		/usr/local/include/qt5/QtCore/qiterator.h \
		/usr/local/include/qt5/QtCore/qlist.h \
		/usr/local/include/qt5/QtCore/qrefcount.h \
		/usr/local/include/qt5/QtCore/qarraydata.h \
		/usr/local/include/qt5/QtCore/qhashfunctions.h \
		/usr/local/include/qt5/QtCore/qstring.h \
		/usr/local/include/qt5/QtCore/qbytearray.h \
		/usr/local/include/qt5/QtCore/qnamespace.h \
		/usr/local/include/qt5/QtCore/qstringliteral.h \
		/usr/local/include/qt5/QtCore/qstringalgorithms.h \
		/usr/local/include/qt5/QtCore/qstringview.h \
		/usr/local/include/qt5/QtCore/qstringbuilder.h \
		/usr/local/include/qt5/QtCore/qpair.h \
		/usr/local/include/qt5/QtCore/qvector.h \
		/usr/local/include/qt5/QtCore/qcontainertools_impl.h \
		/usr/local/include/qt5/QtCore/qpoint.h \
		/usr/local/include/qt5/QtCore/qbytearraylist.h \
		/usr/local/include/qt5/QtCore/qstringlist.h \
		/usr/local/include/qt5/QtCore/qregexp.h \
		/usr/local/include/qt5/QtCore/qstringmatcher.h \
		/usr/local/include/qt5/QtCore/qmap.h \
		/usr/local/include/qt5/QtCore/qtextstream.h \
		/usr/local/include/qt5/QtCore/qiodevice.h \
		/usr/local/include/qt5/QtCore/qobject.h \
		/usr/local/include/qt5/QtCore/qobjectdefs.h \
		/usr/local/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/local/include/qt5/QtCore/qcoreevent.h \
		/usr/local/include/qt5/QtCore/qscopedpointer.h \
		/usr/local/include/qt5/QtCore/qmetatype.h \
		/usr/local/include/qt5/QtCore/qvarlengtharray.h \
		/usr/local/include/qt5/QtCore/qcontainerfwd.h \
		/usr/local/include/qt5/QtCore/qobject_impl.h \
		/usr/local/include/qt5/QtCore/qlocale.h \
		/usr/local/include/qt5/QtCore/qvariant.h \
		/usr/local/include/qt5/QtCore/qshareddata.h \
		/usr/local/include/qt5/QtCore/qset.h \
		/usr/local/include/qt5/QtCore/qcontiguouscache.h \
		/usr/local/include/qt5/QtCore/qsharedpointer.h \
		/usr/local/include/qt5/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stringutils.o src/stringutils.cpp

moc_apputils.o: moc_apputils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_apputils.o moc_apputils.cpp

moc_signalutils.o: moc_signalutils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_signalutils.o moc_signalutils.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/lib || mkdir -p $(INSTALL_ROOT)/usr/local/lib
	$(QINSTALL_PROGRAM) $(TARGET) $(INSTALL_ROOT)/usr/local/lib/$(TARGET)
	-$(STRIP) --strip-unneeded $(INSTALL_ROOT)/usr/local/lib/$(TARGET)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/local/lib/$(TARGET0)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/local/lib/$(TARGET1)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/local/lib/$(TARGET2)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/local/lib/$(TARGET) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/local/lib/$(TARGET0) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/local/lib/$(TARGET1) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/local/lib/$(TARGET2)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/lib/ 


install_headers_/usr/local/include/mere/utils: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/include/mere/utils || mkdir -p $(INSTALL_ROOT)/usr/local/include/mere/utils
	$(QINSTALL) /usr/home/iklash/workspace/mere-utils/mere-utils-lib/src/apputils.h $(INSTALL_ROOT)/usr/local/include/mere/utils/apputils.h
	$(QINSTALL) /usr/home/iklash/workspace/mere-utils/mere-utils-lib/src/envutils.h $(INSTALL_ROOT)/usr/local/include/mere/utils/envutils.h
	$(QINSTALL) /usr/home/iklash/workspace/mere-utils/mere-utils-lib/src/fileutils.h $(INSTALL_ROOT)/usr/local/include/mere/utils/fileutils.h
	$(QINSTALL) /usr/home/iklash/workspace/mere-utils/mere-utils-lib/src/global.h $(INSTALL_ROOT)/usr/local/include/mere/utils/global.h
	$(QINSTALL) /usr/home/iklash/workspace/mere-utils/mere-utils-lib/src/i18nutils.h $(INSTALL_ROOT)/usr/local/include/mere/utils/i18nutils.h
	$(QINSTALL) /usr/home/iklash/workspace/mere-utils/mere-utils-lib/src/iconutils.h $(INSTALL_ROOT)/usr/local/include/mere/utils/iconutils.h
	$(QINSTALL) /usr/home/iklash/workspace/mere-utils/mere-utils-lib/src/processutils.h $(INSTALL_ROOT)/usr/local/include/mere/utils/processutils.h
	$(QINSTALL) /usr/home/iklash/workspace/mere-utils/mere-utils-lib/src/signalutils.h $(INSTALL_ROOT)/usr/local/include/mere/utils/signalutils.h
	$(QINSTALL) /usr/home/iklash/workspace/mere-utils/mere-utils-lib/src/stringutils.h $(INSTALL_ROOT)/usr/local/include/mere/utils/stringutils.h

uninstall_headers_/usr/local/include/mere/utils: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/mere/utils/stringutils.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/mere/utils/signalutils.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/mere/utils/processutils.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/mere/utils/iconutils.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/mere/utils/i18nutils.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/mere/utils/global.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/mere/utils/fileutils.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/mere/utils/envutils.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/include/mere/utils/apputils.h
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/include/mere/utils/ 


install: install_target install_headers_/usr/local/include/mere/utils  FORCE

uninstall: uninstall_target uninstall_headers_/usr/local/include/mere/utils  FORCE

FORCE:

